apiVersion: v1
kind: ConfigMap
metadata:
  name: call-operands
  namespace: kelon
data:
  mongo.yml: |
    call-operands:

      # Relational operands
      - op: eq
        args: 2
        mapping: "$0: $1"
      - op: equal
        args: 2
        mapping: "$0: $1"
      - op: neq
        args: 2
        mapping: "$0: { \"$ne\": $1 }"
      - op: lt
        args: 2
        mapping: "$0: { \"$lt\": $1 }"
      - op: gt
        args: 2
        mapping: "$0: { \"$gt\": $1 }"
      - op: lte
        args: 2
        mapping: "$0: { \"$lte\": $1 }"
      - op: gte
        args: 2
        mapping: "$0: { \"$gte\": $1 }"
  mysql.yml: |-
    call-operands:

      # Mathematical operands
      - op: plus
        args: 2
        mapping: "$0 + $1"
      - op: minus
        args: 2
        mapping: "$0 - $1"
      - op: mul
        args: 2
        mapping: "$1 * $0"
      - op: div
        args: 2
        mapping: "$0 / $1"
      - op: rem
        args: 2
        mapping: "$0 % $1"

      # Relational operands
      - op: eq
        args: 2
        mapping: "$0 = $1"
      - op: equal
        args: 2
        mapping: "$0 = $1"
      - op: neq
        args: 2
        mapping: "$0 != $1"
      - op: lt
        args: 2
        mapping: "$0 < $1"
      - op: gt
        args: 2
        mapping: "$0 > $1"
      - op: lte
        args: 2
        mapping: "$0 <= $1"
      - op: gte
        args: 2
        mapping: "$0 >= $1"

      # Mathematical Functions
      - op: abs
        args: 1
        mapping: "ABS($0)"
  postgres.yml: |-
    call-operands:

      # Mathematical operands
      - op: plus
        args: 2
        mapping: "$0 + $1"
      - op: minus
        args: 2
        mapping: "$0 - $1"
      - op: mul
        args: 2
        mapping: "$1 * $0"
      - op: div
        args: 2
        mapping: "$0 / $1"
      - op: rem
        args: 2
        mapping: "$0 % $1"

      # Relational operands
      - op: eq
        args: 2
        mapping: "$0 = $1"
      - op: equal
        args: 2
        mapping: "$0 = $1"
      - op: neq
        args: 2
        mapping: "$0 != $1"
      - op: lt
        args: 2
        mapping: "$0 < $1"
      - op: gt
        args: 2
        mapping: "$0 > $1"
      - op: lte
        args: 2
        mapping: "$0 <= $1"
      - op: gte
        args: 2
        mapping: "$0 >= $1"

      # Mathematical Functions
      - op: abs
        args: 1
        mapping: "ABS($0)"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongo
  namespace: kelon
data:
  Init-Mongo.js: |-
    db.createUser(
        {
            user   : "You",
            pwd    : "SuperSecure",
            roles  : [
                {
                    role  : "readWrite",
                    db    : "appstore"
                }
            ]
        }
    );

    db.apps.insertOne({id:2,name:"Arnold's App",stars:3,rights:{right:"OWNER",user:{id:1,name:"Arnold",age:72,friend:"John Connor"}}});
    db.apps.insertOne({id:1,name:"First App for everyone",stars:1});
    db.apps.insertOne({id:3,name:"Famous App",stars:5});

    db.users.insertOne({id:1,name:"Arnold",age:72,friend:"John Connor"});
    db.users.insertOne({id:2,name:"Kevin",age:21,friend:"Kevin"});
    db.users.insertOne({id:3,name:"Anyone",friend:"Anyone"});
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mysql
  namespace: kelon
data:
  Init-MySql.sql: "-- Adminer 4.7.3 MySQL dump\n\nSET NAMES utf8;\nSET time_zone
  = '+00:00';\nSET foreign_key_checks = 0;\nSET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';\n\nDROP
  DATABASE IF EXISTS `appstore`;\nCREATE DATABASE `appstore` /*!40100 DEFAULT
  CHARACTER SET latin1 */;\nUSE `appstore`;\n\nDROP TABLE IF EXISTS `apps`;\nCREATE
  TABLE `apps` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `name` varchar(255)
  NOT NULL,\n  `stars` tinyint(3) unsigned zerofill NOT NULL,\n  PRIMARY KEY (`id`)\n)
  ENGINE=InnoDB DEFAULT CHARSET=latin1;\n\nINSERT INTO `apps` (`id`, `name`, `stars`)
  VALUES\n(1,\t'First App for everyone',\t001),\n(2,\t'Arnold\\'s App',\t003),\n(3,\t'Famous
  App',\t005);\n\nDROP TABLE IF EXISTS `app_rights`;\nCREATE TABLE `app_rights`
  (\n  `app_id` int(11) NOT NULL,\n  `user_id` int(11) NOT NULL,\n  `right` varchar(255)
  NOT NULL,\n  KEY `app_id` (`app_id`),\n  KEY `user_id` (`user_id`),\n  CONSTRAINT
  `app_rights_ibfk_1` FOREIGN KEY (`app_id`) REFERENCES `apps` (`id`),\n  CONSTRAINT
  `app_rights_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB
  DEFAULT CHARSET=latin1;\n\nINSERT INTO `app_rights` (`app_id`, `user_id`, `right`)
  VALUES\n(2,\t1,\t'OWNER');\n\nDROP TABLE IF EXISTS `users`;\nCREATE TABLE `users`
  (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `name` varchar(255) NOT NULL,\n
  \ `age` tinyint(4) DEFAULT NULL,\n  `friend` varchar(255) NOT NULL,\n  PRIMARY
  KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1;\n\nINSERT INTO `users` (`id`,
  `name`, `age`, `friend`) VALUES\n(1,\t'Arnold',\t72,\t'John Connor'),\n(2,\t'Kevin',\t21,\t'Kevin'),\n(3,\t'Anyone',\tNULL,\t'Anyone');"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-postgres
  namespace: kelon
data:
  Init-Postgres.sql: "DROP SCHEMA IF EXISTS \"appstore\";\nCREATE SCHEMA \"appstore\";\n\nCREATE
  SEQUENCE apps_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE
  1;\nCREATE TABLE \"appstore\".\"apps\" (\n    \"id\" integer DEFAULT nextval('apps_id_seq')
  NOT NULL,\n    \"name\" character varying(255) NOT NULL,\n    \"stars\" smallint,\n
  \   CONSTRAINT \"apps_id\" PRIMARY KEY (\"id\")\n) WITH (oids = false);\n\nINSERT
  INTO \"appstore\".\"apps\" (\"id\", \"name\", \"stars\") VALUES\n(1,\t'First
  App for everyone',\t1),\n(2,\t'Arnold''s App',\t3),\n(3,\t'Famous App',\t5);\n\nCREATE
  SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE
  1;\nCREATE TABLE \"appstore\".\"users\" (\n    \"id\" integer DEFAULT nextval('users_id_seq')
  NOT NULL,\n    \"name\" character varying(255) NOT NULL,\n    \"age\" smallint,\n
  \   \"friend\" character varying,\n    CONSTRAINT \"users_id\" PRIMARY KEY (\"id\")\n)
  WITH (oids = false);\n\nINSERT INTO \"appstore\".\"users\" (\"id\", \"name\",
  \"age\", \"friend\") VALUES\n(1,\t'Arnold',\t72,\t'John Connor'),\n(2,\t'Kevin',\t21,\t'Kevin'),\n(3,\t'Anyone',\tNULL,\t'Anyone');\n\n\nCREATE
  TABLE \"appstore\".\"app_rights\" (\n    \"app_id\" bigint NOT NULL,\n    \"user_id\"
  bigint NOT NULL,\n    \"right\" character varying NOT NULL,\n    CONSTRAINT
  \"app_rights_app_id_user_id_right\" PRIMARY KEY (\"app_id\", \"user_id\", \"right\"),\n
  \   CONSTRAINT \"app_rights_app_id_fkey\" FOREIGN KEY (app_id) REFERENCES appstore.apps(id)
  NOT DEFERRABLE,\n    CONSTRAINT \"app_rights_user_id_fkey\" FOREIGN KEY (user_id)
  REFERENCES appstore.users(id) NOT DEFERRABLE\n) WITH (oids = false);\n\nINSERT
  INTO \"appstore\".\"app_rights\" (\"app_id\", \"user_id\", \"right\") VALUES\n(2,\t1,\t'OWNER');"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kelon-configs
  namespace: kelon
data:
  api.yml: |
    apis:
      # Route all requests starting with /api/mysql to mysql database
      - path-prefix: /api/mysql
        datastore: mysql
        mappings:
          - path: /apps/.*                   # Matches [GET,POST,PUT,DELETE,PATCH] /api/mysql/apps/.*
            package: applications.mysql
          - path: /apps/[\d]+               # Matches [GET,POST,PUT,DELETE,PATCH] /api/mysql/apps/[\d]+
            package: applications.mysql
          - path: /apps/[\d]+               # Only matches GET /api/mysql/apps/[\d]+
            package: applications.mysql
            methods:
              - GET
          - path: /.*
            package: test
      # Route all requests starting with /api/mongo to MongoDB
      - path-prefix: /api/mongo
        datastore: mongo
        mappings:
          - path: /apps/.*
            package: applications.mongo
      # All other requests are routed to postgres
      - path-prefix: /api/.*?
        datastore: pg
        mappings:
          - path: /apps/.*
            package: applications.pg
  datastore.yml: |-
    # Datastores to connect to
    datastores:
      mysql:
        type: mysql
        connection:
          host: mysql
          port: 3306
          database: appstore
          user: You
          password: SuperSecure

      pg:
        type: postgres
        connection:
          host: postgres-postgresql
          port: 5432
          database: appstore
          user: You
          password: SuperSecure

      mongo:
        type: mongo
        connection:
          host: mongo-mongodb
          port: 27017
          database: appstore
          user: You
          password: SuperSecure

    # Entity-Schemas define the structure of the entities of one schema inside a datastore
    entity_schemas:

      mysql:                                # Target datastore
        appstore:                           # Target schema
          entities:                         # List of all entities of the schema
            - name: users
            - name: app_rights
            - name: apps
            - name: app_tags
            - name: tags

      pg:
        appstore:
          entities:
            - name: users
            - name: app_rights
            - name: apps
            - name: app_tags
            - name: tags

      mongo:
        appstore:
          entities:
            - name: users
            - name: apps
              entities:
                - name: rights
                  entities:
                    - name: user
                      alias: users
  opa.yml: |
    labels:
      app: Kelon
      region: europe-west3
      environment: development

    decision_logs:
      console: true
      reporting:
        min_delay_seconds: 300
        max_delay_seconds: 600

    default_decision: /http/authz/allow
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kelon-policies
  namespace: kelon
data:
  mongo_example.rego: |-
    package applications.mongo

    # Deny all by default
    allow = false

    # Path: GET /api/mongo/apps/:app_id
    # Users with right 'OWNER' on app can access it always
    allow = true {
        input.method = "GET"
        input.path = ["api1", "mongo", "apps", appId]

        # This query fires against collection -> apps
        data.mongo.apps[app].id = appId

        # Nest elements
        data.mongo.rights[right].id = app.id
        data.mongo.users[user].id = right.id

        # Query root
        app.stars > 2

        # Query nested
        right.right = "OWNER"
        user.name = input.user
    }

    # Path: GET /api/mongo/apps/:app_id
    # All apps with 5 stars are public
    allow = true {
        some app, appId
        input.method = "GET"
        input.path = ["api", "mongo", "apps", appId]

        # This query fires against collection -> apps
        data.mongo.apps[app].stars = 5
        app.id = appId
    }

    # Path: GET /api/mongo/apps/:app_id
    # The first app is public
    allow = true {
        input.method = "GET"
        input.path = ["api", "mongo", "apps", "1"]
    }

    # Path: GET <any>
    # All users that are a friends of Kevin are allowed see everything
    allow = true {
        input.method = "GET"

        # This query fires against collection -> users
        data.mongo.users[user].name = input.user
        user.friend = "Kevin"
    }
  mysql_example.rego: |-
    package applications.mysql

    # Deny all by default
    allow = false

    # Path: GET /api/mysql/apps/:app_id
    # Users with right 'OWNER' on app can access it always
    allow = true {
        input.method = "GET"
        input.path = ["api", "mysql", "apps", appId]

        [appId, "OWNER"] = appRights[_]
    }

    # Path: GET /api/mysql/apps/:app_id
    # All apps with 5 stars are public
    allow = true {
        some app, appId
        input.method = "GET"
        input.path = ["api", "mysql", "apps", appId]

        data.mysql.apps[app].stars = 5
        app.id = appId
    }

    # Path: GET /api/mysql/apps/:app_id
    # The first app is public
    allow = true {
        input.method = "GET"
        input.path = ["api", "mysql", "apps", "1"]
    }

    # Path: GET <any>
    # All users that are a friends of Kevin are allowed see everything
    allow = true {
        input.method = "GET"

        # Query
        data.mysql.users[user].name = input.user
        user.friend = "Kevin"
    }

    appRights[[appId, right]] {
        data.mysql.users[u].name = input.user
        right := data.mysql.app_rights[r].right
        appId := r.app_id
        u.id = r.user_id
    }
  pg_example.rego: |-
    package applications.pg

    # Deny all by default
    allow = false

    # Path: GET /api/pg/apps/:app_id
    # Users with right 'OWNER' on app can access it always
    allow = true {
        input.method = "GET"
        input.path = ["api", "pg", "apps", appId]

        [appId, "OWNER"] = appRights[_]
    }

    # Path: GET /api/pg/apps/:app_id
    # All apps with 5 stars are public
    allow = true {
        some app, appId
        input.method = "GET"
        input.path = ["api", "pg", "apps", appId]

        data.pg.apps[app].stars = 5
        app.id = appId
    }

    # Path: GET /api/pg/apps/:app_id
    # The first app is public
    allow = true {
        input.method = "GET"
        input.path = ["api", "pg", "apps", "1"]
    }

    # Path: GET <any>
    # All users that are a friends of Kevin are allowed see everything
    allow = true {
        input.method = "GET"

        # Query
        data.pg.users[user].name = input.user
        user.friend = "Kevin"
    }

    appRights[[appId, right]] {
        data.pg.users[u].name = input.user
        right := data.pg.app_rights[r].right
        appId := r.app_id
        u.id = r.user_id
    }